# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        # Informational only — reports patch coverage without failing the check.
        # The project check enforces actual coverage thresholds.
        informational: true

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
